name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_HUB_NAMESPACE: josepavese
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/base
          push: true
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/daemon-zero-base:latest
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/daemon-zero-base:latest
          cache-to: type=inline

      - name: Update Dockerfile Base Image
        # Switch Dockerfile to use the base image we just built/pushed
        run: |
          sed -i "s|FROM daemon0ai/daemon-zero-base:latest|FROM ${{ env.DOCKER_HUB_NAMESPACE }}/daemon-zero-base:latest|g" docker/run/Dockerfile

      - name: Build and Push App Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/run
          file: ./docker/run/Dockerfile
          build-args: |
             BRANCH=main
          push: true
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/daemon-zero:latest
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/daemon-zero:latest
          cache-to: type=inline
